kind: Deployment
apiVersion: apps/v1
metadata:
  name: petclinic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: sahana179/petclinic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - name: petclinic-port
      port: 8080
      targetPort: 8080
