apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - name: petclinic-port
      port: 8080
      targetPort: 8080
